# Generated by Django 5.2.4 on 2025-07-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('Collection1')
            """,
            """
            DELETE FROM store_collection
            WHERE title='Collection1'
            """
        ),
    ]
