# Generated by Django 5.2.4 on 2025-07-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250707_0408'),
    ]

    operations = [
    ]
