# Generated by Django 5.2.4 on 2025-07-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20250707_0413'),
    ]

    operations = [
    ]
